### ISSUE TITLE
-telnet参数必须要带光猫账号和密码，建议--help里面提示一下吧

### ISSUE THREAD

**Issue by 4331599** [thank243/zteOnu#1]
-telnet参数必须要带光猫账号和密码，建议--help里面提示一下吧
开始没带参数以为会默认使用电信的参数卡了一下第三阶段，我看了一下你的图示带账号密码，但是帖子内容没有明说。
写一下会更适合菜鸟。
`zteOnu.exe -p nE7jA%5m -u telecomadmin -telnet`

**Comment by thank243** [comment]
The telecom's user and password is the default value. In this condition, those params is not necessary.
